# Generated by Django 5.0.6 on 2024-07-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulist_user', '0002_profile_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='username',
        ),
    ]
