# Generated by Django 5.0.6 on 2024-07-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulist_user', '0003_rename_user_name_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_youtube',
        ),
    ]
