# Generated by Django 5.0.6 on 2024-07-16 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulist_user', '0005_profile_location_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_Linkdin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_Twitter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_gith',
        ),
        migrations.AddField(
            model_name='profile',
            name='social_github',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='GitHub Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_linkedin',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='LinkedIn Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Personal Website'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='ulist_user.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_twitter',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter Profile'),
        ),
    ]
