# Generated by Django 5.0.6 on 2024-07-29 12:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulist_user', '0006_remove_profile_social_linkdin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='ulist_user.profile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ulist_user.profile')),
            ],
            options={
                'ordering': ['-is_read', '-sent_at'],
            },
        ),
    ]
