# Generated by Django 5.0.6 on 2024-07-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulist', '0002_tag_review_project_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='vars',
            new_name='value',
        ),
    ]
