# Generated by Django 5.0.6 on 2024-07-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulist', '0003_rename_vars_review_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
