# Generated by Django 5.0.6 on 2024-07-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulist', '0005_project_featured_image'),
        ('ulist_user', '0003_rename_user_name_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ulist_user.profile'),
        ),
    ]
